### ISSUE TITLE
"Bend to clipboard" QS Tile problem

### ISSUE THREAD

**Issue by e-t-l** [elizagamedev/android-textbender#3]
What does it mean to "Bend the clipboard"? I see this phrase in the Readme but it isn't defined.

Textbender's Quick Settings tile is also grayed out, and I cannot find an option to enable it.

Ideally, a Quick Settings tile for Textbender would just enable/disable the overlay to make on-screen text selectable.

**Comment by elizagamedev** [comment]
"Bend the clipboard" means to do whatever action you have assigned in the settings with whatever data is currently stored on the clipboard. If your setting for that is disabled, it will also disable the QS tile.

There are two other pre-existing QS tiles: activate overlay, and toggle floating buttons. Activate overlay is the one you want.
